src/SR/BlogBundle/Entity/Image.php
<?php

namespace SR\BlogBundle\Entity;

use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\HttpFoundation\File\UploadedFile;



/**
 * Image
 *
 * @ORM\Table()
 * @ORM\Entity(repositoryClass="SR\BlogBundle\Entity\Repository\ImageRepository")
 * @ORM\HasLifecycleCallbacks
 */
class Image
{
    /**
     * @var integer
     *
     * @ORM\Column(name="id", type="integer")
     * @ORM\Id
     * @ORM\GeneratedValue(strategy="AUTO")
     */
    private $id;

    /**
     * @var string
     *
     * @ORM\Column(name="url", type="string", length=255)
     */
    private $url;

    /**
     * @var string
     *
     * @ORM\Column(name="alt", type="string", length=255)
     */
    private $alt;

    private $file;

  // On ajoute cet attribut pour y stocker le nom du fichier temporairement
  private $tempFilename;

  // On modifie le setter de File, pour prendre en compte l'upload d'un fichier lorsqu'il en existe déjà un autre
  
  public function getFile()
  {
    return $this->file;
  }


  public function setFile(UploadedFile $file)
  {
    $this->file = $file;
    
    // On vérifie si on avait déjà un fichier pour cette entité
    if (null !== $this->url) {
      // On sauvegarde l'extension du fichier pour le supprimer plus tard
      $this->tempFilename = $this->url;

      // On réinitialise les valeurs des attributs url et alt
      $this->url = null;
      $this->alt = null;
    }
  }

  /**
   * @ORM\PrePersist()
   * @ORM\PreUpdate()
   */
  public function preUpload()
  {
    // Si jamais il n'y a pas de fichier (champ facultatif)
    if (null === $this->file) {
      return;
      
    }

    // Le nom du fichier est son id, on doit juste stocker également son extension
    // Pour faire propre, on devrait renommer cet attribut en « extension », plutôt que « url »
    $this->url = $this->file->guessExtension();

    // Et on génère l'attribut alt de la balise <img>, à la valeur du nom du fichier sur le PC de l'internaute
    $this->alt = $this->file->getClientOriginalName();
  }

  /**
   * @ORM\PostPersist()
   * @ORM\PostUpdate()
   */
  public function upload()
  {
    // Si jamais il n'y a pas de fichier (champ facultatif)
    if (null === $this->file) {
      return;
    }

    // Si on avait un ancien fichier, on le supprime
    if (null !== $this->tempFilename) {
      $oldFile = $this->getUploadRootDir().'/'.$this->id.'.'.$this->tempFilename;
      if (file_exists($oldFile)) {
        unlink($oldFile);
      }
    }

    // On déplace le fichier envoyé dans le répertoire de notre choix
    $this->file->move(
      $this->getUploadRootDir(), // Le répertoire de destination
      $this->id.'.'.$this->url   // Le nom du fichier à créer, ici « id.extension »
    );
  }

  /**
   * @ORM\PreRemove()
   */
  public function preRemoveUpload()
  {
    // On sauvegarde temporairement le nom du fichier, car il dépend de l'id
    $this->tempFilename = $this->getUploadRootDir().'/'.$this->id.'.'.$this->url;
  }

  /**
   * @ORM\PostRemove()
   */
  public function removeUpload()
  {
    // En PostRemove, on n'a pas accès à l'id, on utilise notre nom sauvegardé
    if (file_exists($this->tempFilename)) {
      // On supprime le fichier
      unlink($this->tempFilename);
    }
  }

  public function getUploadDir()
  {
    // On retourne le chemin relatif vers l'image pour un navigateur
    return 'uploads/img';
  }

  protected function getUploadRootDir()
  {
    // On retourne le chemin relatif vers l'image pour notre code PHP
    return __DIR__.'/../../../../web/'.$this->getUploadDir();
  }

  public function getWebPath()    // Permet de retouner le chemin relatif à notre vue, pour que cela soit plus facile à écrire dans notre vue
  {
      return $this->getUploadDir().'/'.$this->getId().'.'.$this->getUrl();
  }

  /**
   * Get id
   *
   * @return integer
   */
  public function getId()
  {
      return $this->id;
  }

  /**
   * Set url
   *
   * @param string $url
   * @return Image
   */
  public function setUrl($url)
  {
      $this->url = $url;

      return $this;
  }

  /**
   * Get url
   *
   * @return string
   */
  public function getUrl()
  {
      return $this->url;
  }

  /**
   * Set alt
   *
   * @param string $alt
   * @return Image
   */
  public function setAlt($alt)
  {
      $this->alt = $alt;

      return $this;
  }

  /**
   * Get alt
   *
   * @return string
   */
  public function getAlt()
  {
      return $this->alt;
  }
}

src/SR/BlogBundle/Form/EventType.php
<?php

namespace SR\BlogBundle\Form;

use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolverInterface;

class EventType extends AbstractType
{
    /**
     * @param FormBuilderInterface $builder
     * @param array $options
     */
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('eventCategory', 'entity',[
                'class'=>'SRBlogBundle:EventCategory',
                'property'=> 'name',
                'multiple'=> false,
                'label' => 'Type d\'événement',
            ])
            ->add('title','text', [
                'label' => 'Titre',
            ])
            ->add('image', new ImageType(), [
                'required'=>false,
            ])
            ->add('content','textarea', [
                'label' => 'Description',
                'attr' => ['cols' => '5', 'rows' => '30'],
                'required'=> true,
            ])
            ->add('postDate','date',  [
                'widget' => 'single_text',
                'format' => 'dd-MM-yyyy',
                'label' => 'Date de publication',
                'attr' => ['class' => 'datepicker']
            ])
            ->add('status','checkbox', [
                'required'=> false,
            ])
            ->add('eventStatus','checkbox', [
                'required'=> false,
            ])
            ->add('eventStartDate','date', [
                'widget' => 'single_text',
                'format' => 'dd-MM-yyyy',
                'label' => 'Date début',
                'attr' => ['class' => 'datepicker']
            ])
            ->add('time_start','time', [
                'widget' => 'choice',
                'attr'=> [
                    'class'=>'form-control'
                ],
                'label' => 'Heure de début',
                'required' => true,
            ])
            ->add('eventEndDate','date', [
                'widget' => 'single_text',
                'format' => 'dd-MM-yyyy',
                'label' => 'Date de fin',
                'attr' => ['class' => 'datepicker'],
                'required' => false,
            ])
            ->add('time_end','time', [
                'widget' => 'choice',
                'attr'=> [
                    'class'=>'form-control'
                ],
                'label' => 'Heure de fin',
                'required' => true,
            ])
            ->add('eventRate','text', [
                'label' => 'Prix',
            ])
            ->add('movies', 'collection', [
                'type' => new MovieType(),
                'by_reference' => false,
                'allow_add' => true,
                'allow_delete'=> true,
            ])
            ->add('eventGuest','text', [
                'required'=> false,
            ])
            ->add('eventLocation','text', [
                'attr'=> [
                    'placeholder' => 'ex: "104 Avenue Jean Lolive, 93500 Pantin"',
                    'required'=> false,
                    'label' => 'Les invités',
                ]
            ])
            ->add('envoyer','submit', [
                'attr' => [
                    'class' => 'btn-info',
                ]
            ])
        ;
    }
    
    /**
     * @param OptionsResolverInterface $resolver
     */
    public function setDefaultOptions(OptionsResolverInterface $resolver)
    {
        $resolver->setDefaults(array(
            'data_class' => 'SR\BlogBundle\Entity\Event'
        ));
    }

    /**
     * @return string
     */
    public function getName()
    {
        return 'sr_blogbundle_event';
    }
}

src/SR/BlogBundle/Controller/EventController.php
<?php

namespace SR\BlogBundle\Controller;

use Symfony\Bundle\FrameworkBundle\Controller\Controller;
use SR\BlogBundle\Entity\Event;
use SR\UserBundle\Entity\User;
use SR\BlogBundle\Entity\Movie;
use SR\BlogBundle\Entity\EventCategory;
use SR\BlogBundle\Form\EventCategoryType;
use SR\BlogBundle\Form\EventType;
use Doctrine\Common\Collections\ArrayCollection;
use Symfony\Component\HttpFoundation\Request;
use \DateTime;

use Sensio\Bundle\FrameworkExtraBundle\Configuration\Security;
use Symfony\Component\Routing\Annotation\Route;

/**
 * EventController : Ce controller permet de gérer les évenements
 *
 * @Route("/evenements")
 */
class EventController extends BlogController
{
    /**
     * Permet d'accéder à la liste des événements d'AHUEFA
     *
     * @Route("/evenement/page/{page}", name="sr_blog_evenement", requirements={"page" = "\d+"}, defaults={"page" = 1} )
     */
    public function indexAction(Request $request, $page)
    {
        $breadcrumbs = $this->get("white_october_breadcrumbs");
        $breadcrumbs->addItem('Accueil', $this->get("router")->generate('sr_blog_home'));
        $breadcrumbs->addItem('événements', $this->get("router")->generate($request->get('_route')));

        $nbPerPage = 3;
        $listEvent = $this->getDoctrine()->getManager()->getRepository('SRBlogBundle:Event')->myFindAll($page, $nbPerPage);
        // On calcule le nombre total de pages grâce au count($listEvent) qui retourne le nombre total d'evenement
        $nbPages = ceil(count($listEvent)/$nbPerPage);
         
        if ($page > $nbPages && $nbPages != 0 ) {
            throw $this->createNotFoundException('Pas de page pour ce numéro de page : '.$page);
        }
        return $this->render('SRBlogBundle:Event:index.html.twig', [
            'listEvent' => $listEvent,
            'nbPages'   => $nbPages,
            'page'      => $page,
        ]);
    }

    /**
     * Permet de récupérer le détail d'un évenement
     *
     * @Route("/evenement/{slug}", name="sr_blog_evenement_view" )
     */
    public function viewAction(Request $request, Event $event, $slug)
    {
        $breadcrumbs = $this->get("white_october_breadcrumbs");
        $breadcrumbs->addItem('Accueil', $this->get("router")->generate('sr_blog_home'));
        $breadcrumbs->addItem('événement', $this->get("router")->generate('sr_blog_evenement'));
        $breadcrumbs->addItem($slug, $this->get("router")->generate($request->get('_route'), [
            'slug' => $slug
        ]));

        if (!$event) {
          throw $this->createNotFoundException('Aucun évenement trouvée pour cet id : '.$event->getId());
        }
        $comments = $this->getDoctrine()->getManager()->getRepository('SRBlogBundle:Comment')->getPostEventComments($event->getId());
        
        return $this->render('SRBlogBundle:Event:view.html.twig', [
            'event' => $event,
            'comments' => $comments
        ]);
    }

    /**
    * Permet d'ajouter un évènement
    *
    * @Route("/add", name="sr_blog_evenement_add", options={"expose" = true} )
    * @Security(" has_role('ROLE_USER')")
    */
    public function addAction(Request $request)
    {
        $event = new Event();
        $form = $this->createForm(new EventType, $event, [
            'action' => $this->generateUrl('sr_blog_evenement_add'),
            'method' => 'POST'
        ]);
        $form->handleRequest($request);

        if($form->isValid()) {
            $user = $this->getUser();
            $event->setUser($user);
            $em = $this->getDoctrine()->getManager();
            $em->persist($event);
            $em->flush();

            return $this->redirect($this->generateUrl('sr_blog_evenement_view', array('slug' => $event->getSlug())));
        }

        return $this->render('SRBlogBundle:Event:add.html.twig',array('form' => $form->createView()));
    }

    /**
    * Permet de mettre à jour un évènement
    *
    * @Route("/evenement/update/{slug}", name="sr_blog_evenement_update", options={"expose" = true} )
    * @Security("has_role('ROLE_USER')")
    */
    public function updateAction(Event $event, Request $request)
    {
        $em = $this->getDoctrine()->getManager();
        if (!$event) {
            throw $this->createNotFoundException('Aucun évenement trouvée pour cet id : '.$event->getId());
        }

        $originalMovies= new ArrayCollection();
        // Crée un tableau contenant les objets Movie courants de la base de données
        foreach ($event->getMovies() as $movie) {
            $originalMovies->add($movie);
        }

        $form = $this->createForm(new EventType, $event, [
            'action' => $this->generateUrl('sr_blog_evenement_update', [
                'slug' => $event->getSlug(),
            ])
        ]);

        if($request->isMethod('POST')) {
            $form->handleRequest($request);
            if($form->isValid()) {
                foreach ($originalMovies as $movie) {
                    
                    if($event->getMovies()->contains($movie) == false) {
                        $em->remove($movie);
                    }
                }
                $em->persist($event);
                $em->flush();             //Pas besoin de persister car doctrine sait qu'il doit le faire (on vient de le récupérer)

                return $this->redirect($this->generateUrl('sr_blog_evenement_view', array('slug' => $event->getSlug())));
            }
    
        }
        return $this->render('SRBlogBundle:Event:update.html.twig', [
            'slug' => $event->getSlug(),
            'form'=> $form->createView(),
        ]);
    }

    /**
     * Permet de supprimer un évènement
     *
     * @Route("/evenement/delete/{slug}", name="sr_blog_evenement_delete", options={"expose" = true} )
     * @Security("has_role('ROLE_USER')")
     */
    public function deleteAction(Event $event, Request $request)
    {
        if (!$event) {
         throw $this->createNotFoundException('Aucun évenement trouvée pour cet id : '.$event->getId());
        }

        $form = $this->createDeleteForm($this->generateUrl('sr_blog_evenement_delete', [
            'slug' => $event->getSlug(),
        ]));
        
        if( $form->handleRequest($request)->isValid()) {
            $em = $this->getDoctrine()->getManager();
            $em->remove($event);
            $em->flush();

            return $this->redirect($this->generateUrl('sr_blog_evenement'));
        }

        return $this->render('SRBlogBundle:Event:delete.html.twig', [
            'event' => $event,
            'form' => $form->createView(),
        ]);
    }

    /**
     * Permet de récupérer les évènements à afficher dans la page d'accueil
     *
     * @Route("/menu", name="menu_event" )
     */
    public function menuAction($limit)
    {
        $listEvent = $this->getDoctrine()->getManager()->getRepository('SRBlogBundle:Event')->getEventHome($limit);

        return $this->render('SRBlogBundle:Event:menu.html.twig',[
            'listEvent' => $listEvent,
        ]);
    }

    /**
     * Permet d'ajouter une nouvelle catégorie pour les événements
     *
     * @Route("/evenements/addCategory", name="sr_blog_evenement_add_category", options={"expose" = true} )
     * @Security("has_role('ROLE_USER')")
     */
    public function addCategoryAction(Request $request)
    {
        $eventCategory = new EventCategory();
        $form = $this->createForm(new EventCategoryType, $eventCategory, [
            'action' => $this->generateUrl('sr_blog_evenement_add_category'),
            'method' => 'POST'
        ]);

        $form->handleRequest($request);

        if($form->isValid()) {

            $em = $this->getDoctrine()->getManager();
            $em->persist($eventCategory);
            $em->flush();

            return $this->redirect($this->generateUrl('sr_blog_evenement'));
        }
        return $this->render('SRBlogBundle:Event:addCategory.html.twig', [
            'form' => $form->createView(),
        ]);
    }
}


src/SR/BlogBundle/Resources/views/Event/add.html.twig
{% extends "SRBlogBundle::modal.html.twig" %}

{% block modal_title %}
    Ajouter un événement
{% endblock %}

{% block modal_body %}

    {{ form(form) }}

{% endblock %}

{% block javascripts %}
{{ parent() }}
{#<script src="//ajax.googleapis.com/ajax/libs/jquery/1.11.1/jquery.min.js"></script>#}

{# Voici le script en question : #}
<script type="text/javascript">
    console.log("toto");
    // On récupère la balise <div> en question qui contient l'attribut « data-prototype » qui nous intéresse.
    var $container = $('div#sr_blogbundle_event_movies');

    // On ajoute un lien pour ajouter un nouveau film
    var $addLink = $('<a href="#" id="add_movie" class="btn btn-default">Ajouter un film</a>');
    $container.append($addLink);

    // On ajoute un nouved
    $addLink.click(function(e) {
      addMovie($container);
      e.preventDefault(); // évite qu'un # apparaisse dans l'URL
      return false;
    });

    // On définit un compteur unique pour nommer les champs qu'on va ajouter dynamiquement
    var index = $container.find(':input').length;

    // On ajoute un premier champ automatiquement s'il n'en existe pas déjà un (cas d'une nouvel article par exemple).
    if (index == 0) {
      addCategory($container);
    } else {
      // Pour chaque film déjà existante, on ajoute un lien de suppression
      $container.children('div').each(function() {
        addDeleteLink($(this));
      });
    }

    // La fonction qui ajoute un formulaire Movie
    function addMovie($container) {
      // Dans le contenu de l'attribut « data-prototype », on remplace :
      // - le texte "__name__label__" qu'il contient par le label du champ
      // - le texte "__name__" qu'il contient par le numéro du champ
      var $prototype = $($container.attr('data-prototype').replace(/__name__label__/g, 'Film n°' + (index+1))
          .replace(/__name__/g, index));

      // On ajoute au prototype un lien pour pouvoir supprimer la catégorie
      addDeleteLink($prototype);

      // On ajoute le prototype modifié à la fin de la balise <div>
      $container.append($prototype);

      // Enfin, on incrémente le compteur pour que le prochain ajout se fasse avec un autre numéro
      index++;
    }

    // La fonction qui ajoute un lien de suppression d'une catégorie
    function addDeleteLink($prototype) {
      // Création du lien
      $deleteLink = $('<a href="#" class="btn btn-danger">Supprimer</a>');

      // Ajout du lien
      $prototype.append($deleteLink);

      // Ajout du listener sur le clic du lien
      $deleteLink.click(function(e) {
        $prototype.remove();

        e.preventDefault(); // évite qu'un # apparaisse dans l'URL

        return false;
      });
    }

</script>
{% endblock %}





src/SR/BlogBundle/Resources/views/Event/index.html.twig
{% extends "SRBlogBundle::layout.html.twig" %}

{% block content %}
          <h2> Nos évenements</h2>
{% if is_granted('ROLE_MODERATEUR') %}
  <div class="space">

    <p><a href="javascript:;" data-target="#addEventModal" data-toggle="modal" class="bouton">Nouvel Evénement</a></p>
    <p><a href="javascript:;" data-target="#addEventTypeModal" data-toggle="modal" class="bouton2">Type Evénement</a></p>

  </div>
{% endif %}
<br><br>
         
<ul>
  {% if listEvent is not empty %}
    <ul class="result-list">
      {%for event in listEvent%}
        <li>
          <div class="result-image">
            <a href="javascript:;">
              {% if event.image is defined and event.image %}
                <img  class="image_news_minature"src="{{ asset(event.image.webPath| apply_filter('miniature')) }}" alt="{{ event.image.alt }}"/>
              {% else %}
                <img  class="image_news_minature"src="{{ asset('bundles/srblog/images/default_event.jpg'| apply_filter('miniature')) }}" alt="default"/>
              {% endif %}
            </a>
          </div>
          <div class="result-info">
            <h4 class="title">
              <a class="titre_index" href= "{{path('sr_blog_evenement_view',{'slug': event.slug})}}">  {{event.title}} </a>
            </h4>
            {#<p class="desc">#}
              {#{{event.content|truncate(300, true, '...')|raw }}#}
            {#</p>#}
            {% if is_granted('ROLE_MODERATEUR') %}
            <div class="btn-row">
              <a title="" href="{{ path('sr_blog_evenement_update', {'slug': event.slug}) }}" data-slug="{{ event.slug }}" data-target="#updateEventModal" data-toggle="modal" data-title="Modifier"><i class="fa fa-fw fa-pencil"></i></a>
              <a title="" href="{{ path('sr_blog_evenement_delete', {'slug': event.slug}) }}" data-slug="{{ event.slug }}" data-target="#deleteEventModal" data-toggle="modal" data-title="Supprimer"><i class="fa fa-fw fa-trash-o"></i></a>
            </div>
            {% endif %}
          </div>
          <div class="result-price">
            <small>Le {{event.eventStartDate|date("d/m/Y") }}</small>
            <a href="{{path('sr_blog_evenement_view',{'slug': event.slug})}}" class="btn btn-inverse btn-block">Voir</a>
          </div>
        </li>
      {% endfor %}
    </ul>
  {% else %}
    <p>Aucun événement</p>
  {% endif %}

  {#MODAL AJOUTER EVENEMENT#}
  <div class="modal fade" id="addEventModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true"></div>
  {#MODAL AJOUTER TYPE EVENEMENT#}
  <div class="modal fade" id="addEventTypeModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true"></div>
  {#MODAL MODIFIER EVENEMENT#}
  <div class="modal fade" id="updateEventModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true"></div>
  {#MODAL SUPPRIMER TYPE EVENEMENT#}
  <div class="modal fade" id="deleteEventModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true"></div>

</ul>

  {% if nbPages > 1 %}
    <ul class="pagination">
      {# On utilise la fonction range(a, b) qui crée un tableau de valeurs entre a et b #}
      {% for p in range(1, nbPages) %}
        <li{% if p == page %} class="active"{% endif %}>
          <a href="{{ path('sr_blog_evenement', {'page': p}) }}">{{ p }}</a>
        </li>
      {% endfor %}
    </ul>
  {% endif %}

{% endblock %}

{% block javascripts %}
  {{ parent() }}
  <script>
    (function(){

      $("#addEventModal").on('show.bs.modal', function(e){

        $.ajax({
          url :  Routing.generate('sr_blog_evenement_add'),
          type : 'GET',
          success : function(html, statut){ // code_html contient le HTML renvoyé
            $("#addEventModal").html(html);
            datepicker();
            wysiwyg();
            addMovie();

          },
          error : function(resultat, statut, erreur){
            console.log("La requète n'a pas abouti")
          }
        });
      });

      $("#addEventTypeModal").on('show.bs.modal', function(e){

        $.ajax({
          url :  Routing.generate('sr_blog_evenement_add_category'),
          type : 'GET',
          success : function(html, statut){ // code_html contient le HTML renvoyé
            $("#addEventTypeModal").html(html);
          },
          error : function(resultat, statut, erreur){
            console.log("La requète n'a pas abouti")
          }
        });
      });

      $("#updateEventModal").on('show.bs.modal', function(e){
        var button = $(e.relatedTarget);
        var slug = button.data('slug');

        $.ajax({
          url :  Routing.generate('sr_blog_evenement_update', {slug: slug} ),
          type : 'GET',
          success : function(html, statut){ // code_html contient le HTML renvoyé
            $("#updateEventModal").html(html);
            datepicker();
            wysiwyg();
          },
          error : function(resultat, statut, erreur){
            console.log("La requète n'a pas abouti")
          }
        });
      });

      $("#deleteEventModal").on('show.bs.modal', function(e){
        var button = $(e.relatedTarget);
        var slug = button.data('slug');

        $.ajax({
          url :  Routing.generate('sr_blog_evenement_delete', {slug: slug} ),
          type : 'GET',
          success : function(html, statut){ // code_html contient le HTML renvoyé
            $("#deleteEventModal").html(html);
          },
          error : function(resultat, statut, erreur){
            console.log("La requète n'a pas abouti")
          }
        });
      });

      {# Fonction qui permet d'utiliser le datepicker bootstrap dans une modal #}
      var datepicker =  function (){

        $('.datepicker').datepicker({
          dateFormat: "dd-mm-yy"
        });
        //Ce code permet d'éviter que l'utilisation du datepicker déclenche l'évenement show.bs.modal.
        $(".datepicker").datepicker().on('show.bs.modal', function(event) {
          event.stopPropagation();
        });
      };

      var wysiwyg = function () {
        $('#sr_blogbundle_event_content').wysihtml5({
          "font-styles": true, //Font styling, e.g. h1, h2, etc. Default true
          "emphasis": true, //Italics, bold, etc. Default true
          "lists": true, //(Un)ordered lists, e.g. Bullets, Numbers. Default true
          "html": false, //Button which allows you to edit the generated HTML. Default false
          "link": true, //Button to insert a link. Default true
          "image": true, //Button to insert an image. Default true,
          "color": true //Button to change color of font
        });
      };

      var addMovie = function(){

        // On récupère la balise <div> en question qui contient l'attribut « data-prototype » qui nous intéresse.
        var $container = $('div#sr_blogbundle_event_movies');

        // On ajoute un lien pour ajouter un nouveau film
        var $addLink = $('<a href="#" id="add_movie" class="btn btn-default">Ajouter un film</a>');
        $container.append($addLink);

        // On ajoute un nouved
        $addLink.click(function(e) {
          addMovie($container);
          e.preventDefault(); // évite qu'un # apparaisse dans l'URL
          return false;
        });

        // On définit un compteur unique pour nommer les champs qu'on va ajouter dynamiquement
        var index = $container.find(':input').length;

        // On ajoute un premier champ automatiquement s'il n'en existe pas déjà un (cas d'une nouvel article par exemple).
        if (index == 0) {
          addCategory($container);
        } else {
          // Pour chaque film déjà existante, on ajoute un lien de suppression
          $container.children('div').each(function() {
            addDeleteLink($(this));
          });
        }

        // La fonction qui ajoute un formulaire Movie
        function addMovie($container) {
          // Dans le contenu de l'attribut « data-prototype », on remplace :
          // - le texte "__name__label__" qu'il contient par le label du champ
          // - le texte "__name__" qu'il contient par le numéro du champ
          var $prototype = $($container.attr('data-prototype').replace(/__name__label__/g, 'Film n°' + (index+1))
                  .replace(/__name__/g, index));

          // On ajoute au prototype un lien pour pouvoir supprimer la catégorie
          addDeleteLink($prototype);

          // On ajoute le prototype modifié à la fin de la balise <div>
          $container.append($prototype);

          // Enfin, on incrémente le compteur pour que le prochain ajout se fasse avec un autre numéro
          index++;
        }

        // La fonction qui ajoute un lien de suppression d'une catégorie
        function addDeleteLink($prototype) {
          // Création du lien
          $deleteLink = $('<a href="#" class="btn btn-danger">Supprimer</a>');

          // Ajout du lien
          $prototype.append($deleteLink);

          // Ajout du listener sur le clic du lien
          $deleteLink.click(function(e) {
            $prototype.remove();

            e.preventDefault(); // évite qu'un # apparaisse dans l'URL

            return false;
          });
        }

      }

    })();

  </script>
{% endblock %}

src/SR/BlogBundle/Resources/views/Event/menu.html.twig
<ul class="sidebar-recent-post">
	{% if listEvent is not empty %}
		{% for event in listEvent %}
			<li>
				<div class="info">
					<h4 class="title"><a href="{{ path('sr_blog_evenement_view', {'slug': event.slug}) }}">{{ event.title }}</a></h4>
					<div class="date">{{event.postDate|localizeddate('none', 'none', null, null, 'd MMMM Y')}}</div>
				</div>
			</li>
		{% endfor %}
	{% else %}
    	<p>Aucun évenement à venir</p></br>
	{% endif %}
</ul>